### ISSUE TITLE
Team Profile

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/gerkelab-com#2]
## @tgerke 

- [x] Bio
- [x] Links
- [x] Photo

## @jhcreed 

- [x] Bio
- [x] Links
- [x] Photo

## @gadenbuie

- [x] Bio
- [x] Links
- [x] Photo

**Comment by tgerke** [comment]
Potentially keep in mind a spot/placeholder for a group photo (I can coordinate this later in July). Also might be good to add Kachi Nwogu as a former member if she would like. She's actually still around through July so could get her in the group shot as well.
